zplug

diff --git a/tag-zsh/zshrc b/tag-zsh/zshrc
--- a/tag-zsh/zshrc
+++ b/tag-zsh/zshrc
@@ -1,123 +1,32 @@
-#!/bin/zsh
+# Plugins
+source ~/.zplug/init.zsh
 
-# Add 'pyenv' to PATH.
-export PYENV_ROOT="$HOME/.pyenv"
-command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
-eval "$(pyenv init -)"
+zplug "spaceship-prompt/spaceship-prompt", use:spaceship.zsh, from:github, as:theme
+zplug "zsh-users/zsh-autosuggestions"
+zplug "zsh-users/zsh-syntax-highlighting"
+zplug "zsh-users/zsh-completions"
+zplug "MichaelAquilina/zsh-you-should-use"
 
+zplug "plugins/sprunge",   		from:oh-my-zsh
+zplug "plugins/colored-man-pages",	from:oh-my-zsh
+zplug "plugins/colored-man-pages",	from:oh-my-zsh
+zplug "plugins/docker",   		from:oh-my-zsh
+zplug "plugins/docker-compose",		from:oh-my-zsh
+zplug "plugins/kubectl",		from:oh-my-zsh
+zplug "plugins/fzf", 			from:oh-my-zsh
+zplug "plugins/nmap", 			from:oh-my-zsh
 
-
-if command -v thefuck > /dev/null 2>&1; then
-export GEM_HOME="$(ruby -e 'puts Gem.user_dir')"
-export PATH="$PATH:$GEM_HOME/bin"
-fi
-
-# Enable shims and autocompletion for pyenv.
-if command -v pyenv -v > /dev/null 2>&1; then
-eval "$(pyenv init --path)"
-# Load pyenv-virtualenv automatically by adding
-# # the following to ~/.zshrc:
-#
-eval "$(pyenv virtualenv-init -)"
-fi
-# Load pyenv-virtualenv automatically by adding
-# # the following to ~/.zshrc:
-#
-eval "$(pyenv virtualenv-init -)"
-
-eval "$(zoxide init zsh)"
-
-# Sets term colors, and fixes problems with SSH for pywal/wpg
-if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
-  SESSION_TYPE=remote/ssh
-else
-  case $(ps -o comm= -p $PPID) in
-    sshd|*/sshd) SESSION_TYPE=remote/ssh;;
-  esac
-    # Only change term colors for local system
-    if [ -f ${XDG_CONFIG_HOME}/wpg/sequences ]; then
-      #command cat ${XDG_CONFIG_HOME}/wpg/sequences
-    fi
-    if [ -f ~/.cache/wal/sequences ]; then
-      command cat ${HOME}/.cache/wal/sequences
+# Install plugins if there are plugins that have not been installed
+if ! zplug check --verbose; then
+    printf "Install? [y/N]: "
+    if read -q; then
+        echo; zplug install
     fi
 fi
 
-if command -v thefuck > /dev/null 2>&1; then
-  eval $(thefuck --alias)
+zplug load --verbose
 
-else
-    echo 'thefuck not found'
-fi
-if [ -e $HOME/antigen.zsh ]; then
-source ~/antigen.zsh
-
-antigen bundle git
-antigen bundle pip
-antigen bundle zsh-users/zsh-completions
-antigen bundle zsh-users/zsh-autosuggestions
-antigen bundle zsh-users/zsh-syntax-highlighting
-antigen bundle sprunge
-antigen bundle vi-mode
-antigen bundle key-bindings
-antigen bundle colored-man-pages
-antigen bundle tmuxinator
-antigen bundle docker
-antigen bundle docker-compose
-antigen bundle dbz/kube-aliases
-antigen bundle fzf
-antigen bundle mosh
-antigen bundle nmap
-antigen bundle perms
-antigen bundle virtualenvwrapper
-antigen bundle "MichaelAquilina/zsh-you-should-use"
-antigen bundle dotenv
-antigen bundle sunlei/zsh-ssh
-antigen bundle command-not-found
-
-antigen apply
-
-else
-    echo 'Antigen not found install using curl -L git.io/antigen > antigen.zsh'
-fi
-# The Fuck
-if command -v thefuck > /dev/null 2>&1; then
-  eval $(thefuck --alias)
-fi
-
-# Configure vi mode for plugin
-VI_MODE_RESET_PROMPT_ON_MODE_CHANGE=true
-VI_MODE_SET_CURSOR=true
-
-# Change cursor shape for different vi modes.
-function zle-keymap-select {
-  if [[ ${KEYMAP} == vicmd ]] ||
-     [[ $1 = 'block' ]]; then
-    echo -ne '\e[1 q'
-  elif [[ ${KEYMAP} == main ]] ||
-       [[ ${KEYMAP} == viins ]] ||
-       [[ ${KEYMAP} = '' ]] ||
-       [[ $1 = 'beam' ]]; then
-    echo -ne '\e[5 q'
-  fi
-}
-zle -N zle-keymap-select
-zle-line-init() {
-    zle -K viins # initiate `vi insert` as keymap (can be removed if `bindkey -V` has been set elsewhere)
-    echo -ne "\e[5 q"
-}
-zle -N zle-line-init
-echo -ne '\e[5 q' # Use beam shape cursor on startup.
-preexec() { echo -ne '\e[5 q' ;} # Use beam shape cursor for each new prompt.
-PATH="$HOME/.local/bin:$PATH"
-
-# Let jobs continue even if shell exits
-setopt NO_HUP
-
-# Add 'pyenv' to PATH.
-export PYENV_ROOT="$HOME/.pyenv"
-export PATH="$PYENV_ROOT/bin:$PATH"
-
+# History
 HISTSIZE=5000               #How many lines of history to keep in memory
 HISTFILE=~/.zsh_history     #Where to save history to disk
 SAVEHIST=5000               #Number of history entries to save to disk
@@ -126,33 +35,20 @@ setopt    appendhistory     #Append history to the history file (no overwriting)
 setopt    sharehistory      #Share history across terminals
 setopt    incappendhistory  #Immediately append to the history file, not just when a term is killed
 
+# Zoxide
+eval "$(zoxide init zsh)"
 
-if [ -e $HOME/.keybinds ]; then
-    source $HOME/.keybinds
-else
-    echo '.keybinds not found'
+# The Fuck
+if command -v thefuck > /dev/null 2>&1; then
+  eval $(thefuck --alias)
 fi
 
 
-if [ -e $HOME/.zsh_aliases ]; then
-    source $HOME/.zsh_aliases
-else
-    echo '.zsh_aliases not found'
-fi
-
-if command -v starship > /dev/null 2>&1; then
-  eval "$(starship init zsh)"
-else
-  echo 'Install Starship Prompt https://starship.rs/'
-fi
+# Let jobs continue even if shell exits
+setopt NO_HUP
 
 
-if command -v neofetch > /dev/null 2>&1; then
-  clear 
-  neofetch
-else
-  echo 'Install Neofetch'
-fi
+
 
 # Add local tools to PATH
 test -e "${HOME}/.scripts" && PATH="${HOME}/.scripts:${PATH}"
@@ -167,6 +63,24 @@ if [ "${IS_MAC}" = "1" ]; then
   test -e "${HOME}/.local/share/gem/ruby/3.0.0/bin" && PATH="${HOME}/.local/share/gem/ruby/3.0.0/bin:${PATH}"
 fi
 
+# Python
+export PATH="$HOME/.poetry/bin:$PATH"
+export PATH=$PATH:$HOME/bin
+
+# Enable shims and autocompletion for pyenv.
+if command -v pyenv -v > /dev/null 2>&1; then
+  export PYENV_ROOT="$HOME/.pyenv"
+  command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
+  eval "$(pyenv init -)"
+  eval "$(pyenv virtualenv-init -)"
+fi
+
+# Aliases
+if [ -e $HOME/.zsh_aliases ]; then
+    source $HOME/.zsh_aliases
+else
+    echo '.zsh_aliases not found'
+fi
 
 ### START-Keychain ###
 # Let  re-use ssh-agent and/or gpg-agent between logins
@@ -175,9 +89,13 @@ source $HOME/.keychain/$HOST-sh
 ### End-Keychain ###
 
 
-#if [ -z "$TMUX" ]; then
-#    tmux attach -t default || tmux new -s default
-#fi
+if command -v neofetch > /dev/null 2>&1; then
+  clear 
+  neofetch
+else
+  echo 'Install Neofetch'
+fi
 
-export PATH="$HOME/.poetry/bin:$PATH"
-export PATH=$PATH:$HOME/bin
+
+
+source /home/glen/.config/broot/launcher/bash/br
